In [10]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC

import pandas as pd

In [11]:
df = pd.read_csv("Zips.csv")
#df['TV_Avail']='Unknown'
display(df)
yes_count =0
no_count =0

              Zip
0           06390
1           06468
2           06470
3           06482
4           06484
5           06604
6           06605
7           06606
8           06607
9           06608
10          06610
11          06611
12          06612
13          06614
14          06615
15          06784
16          06801
17          06804
18          06807
19          06810
20          06811
21          06812
22          06820
23          06824
24          06825
25          06830
26          06831
27          06840
28          06850
29          06851
...           ...
1054        12779
1055        12780
1056        12783
1057        12785
1058        12786
1059        12787
1060        12788
1061        12789
1062        12790
1063        12791
1064        12792
1065        18302
1066        18324
1067        18325
1068        18328
1069        18336
1070        18337
1071        18340
1072        18371
1073        18405
1074        18425
1075        18426
1076        18428
1077        18435
1078        18445
1079        18451
1080        18458
1081        18464
1082  Grand Total
1083   Total Zips

[1084 rows x 1 columns]

In [12]:

def CheckAvail(zipcode):
    options = webdriver.ChromeOptions()
#     options.add_argument('--headless')
#     options.add_argument('window-size=1200x600')
    
    browser = webdriver.Chrome('C:\\Users\\Arslan Shahid\\Desktop\\chromedriver')
    browser.get("https://www.layer3tv.com/get-layer3")
#     browser = webdriver.PhantomJS('C:\\Users\\Arslan Shahid\\Desktop\\phantomjs-2.1.1-windows\\bin\\phantomjs')
#     browser.get("https://www.layer3tv.com/get-layer3")

    #print(browser.title)
    FirstTitle = browser.title
    #browser.implicitly_wait(3)
    #print(browser.title)
    elem = WebDriverWait(browser, 5).until(EC.presence_of_element_located((By.ID, "PostalCode")))
    elem.clear()
    #elem.send_keys('07078')
    elem.send_keys(zipcode)
    button1 = WebDriverWait(browser, 5).until(EC.presence_of_element_located((By.ID, "signupbutton-landing")))
    #butt = browser.find_element_by_id("signupbutton-landing")
    button1.submit()
    #button1.send_keys(Keys.ENTER)
    #print("lol0")
    #browser.implicitly_wait(3)
    
    elem.send_keys(Keys.ENTER)
    #print("lol1")
    try:
            
        #print("lol")
        button = WebDriverWait(browser, 10).until(EC.presence_of_element_located((By.ID, "signupbutton-offer")))
#         yes_count+=1
        #print("Here")
#         return 'Yes'
    except:
        dummy=0
       # button = WebDriverWait(browser, 10).until(EC.presence_of_element_located((By.ID, "showlineup1-offer-legacy")))
        
        
    #print("lol")
    #print("catched")
    
    #elem.send_keys(Keys.ENTER)
    SecondTitle = browser.title
    browser.quit()
    if(SecondTitle == FirstTitle):
        #no_count+=1
        return 'No'
    else:
        #yes_count+=1
        return 'Yes'
    #print(browser.title)

In [13]:
#print(CheckAvail('07094'))
#print(CheckAvail('06390'))

In [15]:
data = pd.read_csv('Result.csv')
#print(data['0'].count())
Avail = [x for x in data['TV_Avail']]
LIMIT =50
length =data['TV_Avail'].count()-1
Current =0
ErrorCount =0
Curr =""
for zipcode in df['Zip'][length:]:
    Curr =""
    #dummy =0
    try:
        Curr = CheckAvail(zipcode)
       # print(Curr)
        Avail.append(Curr)
    except:
        Avail.append("ERROR")
        ErrorCount+=1
        
        #Curr ="ERROR"
        
    
    Current+=1
    if(Current ==LIMIT or ErrorCount>0):
        print('DONE ',Current,"Errors",ErrorCount," ",Curr)
        break
    if(Current%10==0):
        
        print('DONE ',Current,"Errors",ErrorCount," ",Curr,"Zip ",zipcode)
#         yes_count=0
#         no_count=0
        ErrorCount=0
#     print('DONE ',Current)
    #print(zipcode)
    #print('DONE ',Current,"Errors",ErrorCount," ",Curr,"Zip ",zipcode)
    
        
    
Avail = pd.Series(Avail)
#display(Avail)
tdf = pd.DataFrame({'TV_Avail' : Avail})
tdf.to_csv("Result.csv",index=False)
display(tdf)

DONE  10 Errors 0   Yes Zip  11362
DONE  20 Errors 0   Yes Zip  11372
DONE  30 Errors 0   Yes Zip  11413
DONE  40 Errors 0   Yes Zip  11423
DONE  50 Errors 0   Yes

    TV_Avail
0      ERROR
1         No
2         No
3         No
4      ERROR
5         No
6         No
7         No
8      ERROR
9         No
10        No
11        No
12        No
13     ERROR
14        No
15     ERROR
16        No
17        No
18        No
19        No
20        No
21        No
22        No
23        No
24        No
25        No
26        No
27        No
28        No
29        No
..       ...
737      Yes
738      Yes
739      Yes
740      Yes
741      Yes
742      Yes
743      Yes
744      Yes
745      Yes
746      Yes
747      Yes
748      Yes
749      Yes
750      Yes
751      Yes
752      Yes
753      Yes
754      Yes
755      Yes
756      Yes
757      Yes
758      Yes
759      Yes
760      Yes
761      Yes
762      Yes
763      Yes
764      Yes
765      Yes
766      Yes

[767 rows x 1 columns]